### PR TITLE
Add support for multiple kernel bases

### PR DESCRIPTION
**Pull request by peacey**
Hi @FossoresLP,

I am working with @tusc on adding unifios support to the wireguard-vyatta-ubnt repository. I know it's been 2 months since you made this repository, so I hope you are still interested in merging this to the official repo. 

Let me start by thanking you for already doing most of the hard work in merging the unifios build scripts into your CI workflow. Since you made this repo, Ubiquiti has updated the UDMP several times, and a couple of times they introduced an entirely new kernel. To speed up the build, we divided the build into kernel bases, where each kernel base is used to compile several local versions with the kernel headers of that base. 

In this PR, I have updated your unifios build script and environment to support compiling the module for multiple kernel bases. I have also removed unnecessary utilities likes iftop from the build. The only tools included are wireguard, bash, openresolv, and qrencode. 

The build [as you can see here](https://github.com/peacey/wireguard-vyatta-ubnt/actions/runs/1028302301) takes ~40 minutes to complete, downloads ~450 MB of data from an S3 bucket (the kernel headers for each base), and compiles 12 different kernel versions of the module across 3 kernel bases. Each base is compiled in parallel since they are defined in a matrix, but the local versions for each base are compiled sequentially within that base. The build generates the release_unifios artifact, which I have tested successfully on several versions of the UDMP.

I did try to parallelize the local versions as well as the bases, and it was around 5 minutes faster, but uses 4 times as much data (~2 GB) from the S3 bucket since it has to download the kernel headers for each kernel local version instead of each kernel base. So I did not think that was worth it. [Here is a link](https://github.com/peacey/wireguard-vyatta-ubnt/actions/runs/1028535826) to the fully parallelized build if you're curious. 

Please tell me your thoughts and if any further changes are needed to get this merged. As I said, the generated release_unifios artifact works on the UDM. The only thing left is to make a release out of the artifact and an entry in the README, but I was not sure how you wanted to handle that in conjunction with the vyatta modules.

Thank you so much for putting the time into this work. We really appreciate it. 

Regards,
Peacey

### CODE REVIEW

**Comment by FossoresLP** [comment]
Hi @peacey,

Thanks for your work on this.

I'll take a closer look soon, but so far this looks good to me.

If I don't find any issues, I'll get this into the official repo and split some of the documentation from the readme so that both versions can coexist a little easier.

Just for future reference, who owns the S3 bucket?
It's not ideal from a security standpoint to just pull the kernel from an unknown source, so I'd like to inform the users where it comes from.

**Comment by peacey** [comment]
Thanks for the quick response, Pascal.

The S3 bucket is owned by me (I'm not affiliated with any organization). You can re-host the headers wherever you think is best and we can change the URLs easily. It's costing around $0.02 on S3 per build (450 MB in outgoing data charges for each build), which is basically nothing. So I didn't mind hosting them for testing purposes.

**Comment by FossoresLP** [comment]
Sorry for the delay, this PR looks good so I'm going to merge it.
I'm a little busy right now so I'm not quite sure when I'm going to be able tune the release process but rest assured this will be merged into the main repo as soon as I find the time.

**Comment by FossoresLP** [comment]
@peacey Since I never expected someone to send a PR against my development branch for UDM support, I did not plan on merging this directly into the main repo.
Would it be ok for you, if I reworked the UDM support into a single commit? This would of course mean that there would not be detailed attribution for your work on this. Instead I would mention you and tusc in the commit message.

**Comment by peacey** [comment]
Hi @FossoresLP,

Please do whatever works best for you. We are fine having the attribution in the commit if that's the best way forward.

However, in the future when new software versions for the UDMP come out, can I do a pull request directly to the main repo to add support for the new versions every once in a while? We just need to update the versions.txt in the right base, or add new bases as they come out. 

Regards,
Tarek

**Comment by FossoresLP** [comment]
@peacey You can always open PRs against the main repo for updates. This is actually greatly appreciated since I'm unable to test UDM builds.
The only reason I'd like to add the initial support as a single commit is my messed up commit history (including some LFS files at some point) that I would like to keep out of the main repo.

**Comment by peacey** [comment]
No worries Pascal. I completely understand. Please go ahead and do the single commit :)

**Pull request merged**
